plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "coverage/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - "Gemfile.lock"

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30
  Exclude:
    - "spec/**/*"

Metrics/AbcSize:
  Max: 30
  Exclude:
    - "spec/**/*"

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Metrics/ClassLength:
  Max: 300

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"
    - "Rakefile"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Naming/AccessorMethodName:
  Enabled: false

RSpec/ExampleLength:
  Max: 60

RSpec/MultipleExpectations:
  Max: 6

RSpec/InstanceVariable:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/NestedGroups:
  Max: 4
